const filme = [
  "Encanto", "Bacurau", "Cidade de Deus", "Central do Brasil"
]

// 1° valor = 1
// 2° valor = ...
// 3° valor = ...
// 4° valor = ...
// 5° valor = ...
// 6° valor = ...

for (let valor of filme) {
  console.log(valor)
}